export const PERSISTENCE_SCHEMA_VERSION = 1;
export const SQLITE_BUSY_TIMEOUT_MS = 5_000;
export const MAX_PERSISTED_IDENTIFIER_CHARACTERS = 128;
export const MAX_PERSISTED_TEXT_INPUT_CHARACTERS = 65_536;
export const MAX_PERSISTED_SUMMARY_CHARACTERS = 4_096;
export const REDACTED_VALUE = "[REDACTED]";

export type PersistenceErrorCode =
  | "INVALID_PERSISTENCE_INPUT"
  | "SESSION_NOT_FOUND"
  | "INVALID_EVENT_SEQUENCE"
  | "DUPLICATE_RECORD"
  | "UNSUPPORTED_SCHEMA_VERSION"
  | "REPOSITORY_CLOSED"
  | "PERSISTENCE_FAILED";
